// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFilesDialog() {
  return window['go']['main']['App']['AddFilesDialog']();
}

export function AddFolderDialog() {
  return window['go']['main']['App']['AddFolderDialog']();
}

export function AddPaths(arg1) {
  return window['go']['main']['App']['AddPaths'](arg1);
}

export function CancelClean() {
  return window['go']['main']['App']['CancelClean']();
}

export function ClearFiles() {
  return window['go']['main']['App']['ClearFiles']();
}

export function ExportMetadataCSV() {
  return window['go']['main']['App']['ExportMetadataCSV']();
}

export function ExportPrivacyReportJSON() {
  return window['go']['main']['App']['ExportPrivacyReportJSON']();
}

export function GetEngineStatus() {
  return window['go']['main']['App']['GetEngineStatus']();
}

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function OpenOutputFolder(arg1) {
  return window['go']['main']['App']['OpenOutputFolder'](arg1);
}

export function RemoveFiles(arg1) {
  return window['go']['main']['App']['RemoveFiles'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectOutputFolder() {
  return window['go']['main']['App']['SelectOutputFolder']();
}

export function StartClean(arg1) {
  return window['go']['main']['App']['StartClean'](arg1);
}
