// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';

export function AddFilesDialog():Promise<Array<model.FileEntry>>;

export function AddFolderDialog():Promise<Array<model.FileEntry>>;

export function AddPaths(arg1:Array<string>):Promise<Array<model.FileEntry>>;

export function CancelClean():Promise<void>;

export function ClearFiles():Promise<void>;

export function ExportMetadataCSV():Promise<string>;

export function ExportPrivacyReportJSON():Promise<string>;

export function GetEngineStatus():Promise<main.EngineStatus>;

export function GetFiles():Promise<Array<model.FileEntry>>;

export function GetSettings():Promise<model.Settings>;

export function OpenOutputFolder(arg1:string):Promise<void>;

export function RemoveFiles(arg1:Array<string>):Promise<void>;

export function SaveSettings(arg1:model.Settings):Promise<void>;

export function SelectOutputFolder():Promise<string>;

export function StartClean(arg1:model.CleanRequest):Promise<void>;
